// Generated by gencpp from file pkgInt/triangle.msg
// DO NOT EDIT!


#ifndef PKGINT_MESSAGE_TRIANGLE_H
#define PKGINT_MESSAGE_TRIANGLE_H

#include <ros/service_traits.h>


#include <pkgInt/triangleRequest.h>
#include <pkgInt/triangleResponse.h>


namespace pkgInt
{

struct triangle
{

typedef triangleRequest Request;
typedef triangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct triangle
} // namespace pkgInt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkgInt::triangle > {
  static const char* value()
  {
    return "4e625ac4adc31256378a5e593887ac09";
  }

  static const char* value(const ::pkgInt::triangle&) { return value(); }
};

template<>
struct DataType< ::pkgInt::triangle > {
  static const char* value()
  {
    return "pkgInt/triangle";
  }

  static const char* value(const ::pkgInt::triangle&) { return value(); }
};


// service_traits::MD5Sum< ::pkgInt::triangleRequest> should match 
// service_traits::MD5Sum< ::pkgInt::triangle > 
template<>
struct MD5Sum< ::pkgInt::triangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkgInt::triangle >::value();
  }
  static const char* value(const ::pkgInt::triangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkgInt::triangleRequest> should match 
// service_traits::DataType< ::pkgInt::triangle > 
template<>
struct DataType< ::pkgInt::triangleRequest>
{
  static const char* value()
  {
    return DataType< ::pkgInt::triangle >::value();
  }
  static const char* value(const ::pkgInt::triangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkgInt::triangleResponse> should match 
// service_traits::MD5Sum< ::pkgInt::triangle > 
template<>
struct MD5Sum< ::pkgInt::triangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkgInt::triangle >::value();
  }
  static const char* value(const ::pkgInt::triangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkgInt::triangleResponse> should match 
// service_traits::DataType< ::pkgInt::triangle > 
template<>
struct DataType< ::pkgInt::triangleResponse>
{
  static const char* value()
  {
    return DataType< ::pkgInt::triangle >::value();
  }
  static const char* value(const ::pkgInt::triangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKGINT_MESSAGE_TRIANGLE_H
