// Generated by gencpp from file capra_msgs/LandoltGap.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_LANDOLTGAP_H
#define CAPRA_MSGS_MESSAGE_LANDOLTGAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <capra_msgs/BoundingCircle.h>

namespace capra_msgs
{
template <class ContainerAllocator>
struct LandoltGap_
{
  typedef LandoltGap_<ContainerAllocator> Type;

  LandoltGap_()
    : gap()
    , angle(0.0)  {
    }
  LandoltGap_(const ContainerAllocator& _alloc)
    : gap(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::capra_msgs::BoundingCircle_<ContainerAllocator>  _gap_type;
  _gap_type gap;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::capra_msgs::LandoltGap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_msgs::LandoltGap_<ContainerAllocator> const> ConstPtr;

}; // struct LandoltGap_

typedef ::capra_msgs::LandoltGap_<std::allocator<void> > LandoltGap;

typedef boost::shared_ptr< ::capra_msgs::LandoltGap > LandoltGapPtr;
typedef boost::shared_ptr< ::capra_msgs::LandoltGap const> LandoltGapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_msgs::LandoltGap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_msgs::LandoltGap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'capra_msgs': ['/home/samuel/Documents/projetInt/src/capra_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::LandoltGap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::LandoltGap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::LandoltGap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::LandoltGap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::LandoltGap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::LandoltGap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_msgs::LandoltGap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e42544d4bf49c88860dcd0d93bd66c45";
  }

  static const char* value(const ::capra_msgs::LandoltGap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe42544d4bf49c888ULL;
  static const uint64_t static_value2 = 0x60dcd0d93bd66c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_msgs::LandoltGap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_msgs/LandoltGap";
  }

  static const char* value(const ::capra_msgs::LandoltGap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_msgs::LandoltGap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BoundingCircle gap\n\
float64 angle\n\
================================================================================\n\
MSG: capra_msgs/BoundingCircle\n\
int64 xcenter\n\
int64 ycenter\n\
float64 radius\n\
";
  }

  static const char* value(const ::capra_msgs::LandoltGap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_msgs::LandoltGap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gap);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandoltGap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_msgs::LandoltGap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_msgs::LandoltGap_<ContainerAllocator>& v)
  {
    s << indent << "gap: ";
    s << std::endl;
    Printer< ::capra_msgs::BoundingCircle_<ContainerAllocator> >::stream(s, indent + "  ", v.gap);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_LANDOLTGAP_H
