// Generated by gencpp from file capra_msgs/Landolts.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_LANDOLTS_H
#define CAPRA_MSGS_MESSAGE_LANDOLTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <capra_msgs/LandoltGap.h>

namespace capra_msgs
{
template <class ContainerAllocator>
struct Landolts_
{
  typedef Landolts_<ContainerAllocator> Type;

  Landolts_()
    : header()
    , image_header()
    , gaps()  {
    }
  Landolts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , gaps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::capra_msgs::LandoltGap_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::capra_msgs::LandoltGap_<ContainerAllocator> >::other >  _gaps_type;
  _gaps_type gaps;





  typedef boost::shared_ptr< ::capra_msgs::Landolts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_msgs::Landolts_<ContainerAllocator> const> ConstPtr;

}; // struct Landolts_

typedef ::capra_msgs::Landolts_<std::allocator<void> > Landolts;

typedef boost::shared_ptr< ::capra_msgs::Landolts > LandoltsPtr;
typedef boost::shared_ptr< ::capra_msgs::Landolts const> LandoltsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_msgs::Landolts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_msgs::Landolts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'capra_msgs': ['/home/samuel/Documents/projetInt/src/capra_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::Landolts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::Landolts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::Landolts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::Landolts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::Landolts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::Landolts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_msgs::Landolts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4d34173e5d16e0e6f807e704e0367f0";
  }

  static const char* value(const ::capra_msgs::Landolts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4d34173e5d16e0eULL;
  static const uint64_t static_value2 = 0x6f807e704e0367f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_msgs::Landolts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_msgs/Landolts";
  }

  static const char* value(const ::capra_msgs::Landolts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_msgs::Landolts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Header image_header\n\
LandoltGap[] gaps\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: capra_msgs/LandoltGap\n\
BoundingCircle gap\n\
float64 angle\n\
================================================================================\n\
MSG: capra_msgs/BoundingCircle\n\
int64 xcenter\n\
int64 ycenter\n\
float64 radius\n\
";
  }

  static const char* value(const ::capra_msgs::Landolts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_msgs::Landolts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.gaps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landolts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_msgs::Landolts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_msgs::Landolts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "gaps[]" << std::endl;
    for (size_t i = 0; i < v.gaps.size(); ++i)
    {
      s << indent << "  gaps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::capra_msgs::LandoltGap_<ContainerAllocator> >::stream(s, indent + "    ", v.gaps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_LANDOLTS_H
