// Generated by gencpp from file integration/triangle.msg
// DO NOT EDIT!


#ifndef INTEGRATION_MESSAGE_TRIANGLE_H
#define INTEGRATION_MESSAGE_TRIANGLE_H

#include <ros/service_traits.h>


#include <integration/triangleRequest.h>
#include <integration/triangleResponse.h>


namespace integration
{

struct triangle
{

typedef triangleRequest Request;
typedef triangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct triangle
} // namespace integration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::integration::triangle > {
  static const char* value()
  {
    return "4e625ac4adc31256378a5e593887ac09";
  }

  static const char* value(const ::integration::triangle&) { return value(); }
};

template<>
struct DataType< ::integration::triangle > {
  static const char* value()
  {
    return "integration/triangle";
  }

  static const char* value(const ::integration::triangle&) { return value(); }
};


// service_traits::MD5Sum< ::integration::triangleRequest> should match 
// service_traits::MD5Sum< ::integration::triangle > 
template<>
struct MD5Sum< ::integration::triangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::integration::triangle >::value();
  }
  static const char* value(const ::integration::triangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::integration::triangleRequest> should match 
// service_traits::DataType< ::integration::triangle > 
template<>
struct DataType< ::integration::triangleRequest>
{
  static const char* value()
  {
    return DataType< ::integration::triangle >::value();
  }
  static const char* value(const ::integration::triangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::integration::triangleResponse> should match 
// service_traits::MD5Sum< ::integration::triangle > 
template<>
struct MD5Sum< ::integration::triangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::integration::triangle >::value();
  }
  static const char* value(const ::integration::triangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::integration::triangleResponse> should match 
// service_traits::DataType< ::integration::triangle > 
template<>
struct DataType< ::integration::triangleResponse>
{
  static const char* value()
  {
    return DataType< ::integration::triangle >::value();
  }
  static const char* value(const ::integration::triangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTEGRATION_MESSAGE_TRIANGLE_H
